common: &common
    num_kpts: 98
    crop_size: 256
train_param:
    batch_size: 16
    workers: 4
    pdb_bins: 0
    criterion:
        type: L1
    optimizer:
        type: RMSprop
        kwargs:
            lr: 0.00025
    scheduler:
        milestones: [80, 120]
        gamma: 0.2
        epochs: 150
    scale_min: 0.9
    scale_max: 1.1
    mirror: true
    rotation: 30
    translate_rate: 0.0781
    normalize: standard
    train_root: /mnt/lustre/share/zhubeier/WFLW/train/Image/
    train_source: /mnt/lustre/share/zhubeier/WFLW/train/train_98pt.txt
    print_freq: 30
    snapshot_freq: 2
    use_weights: false
    <<: *common
test_param:
    batch_size: 64 
    workers: 4
    val_root: /mnt/lustre/share/zhubeier/WFLW/test/Image
    val_source: /mnt/lustre/share/zhubeier/WFLW/test/test_98pt.txt 
    <<: *common
MODEL:
  NAME: 'hrnet'
  NUM_JOINTS: 98
  BG: false
  INIT_WEIGHTS: true
  PRETRAINED: '/mnt/lustre/share/zhubeier/pretrained_model/hrnetv2_w18_imagenet_pretrained.pth'
  SIGMA: 1.0 
  IMAGE_SIZE:
    - 256
    - 256
  HEATMAP_SIZE:
    - 64
    - 64
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
        - 72
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
        - 72
        - 144
      FUSE_METHOD: SUM




